#!/bin/bash

#############
# CONSTANTS #
#############

ORIGWD=$(pwd)
SCRIPTDIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
SCANREPOS=$SCRIPTDIR/../scan-repos

#########
# CHECK #
#########

function check {

	local testfct=$1
	shift

	# Run test
	echo -n $testfct "$@" ...
	test_output=$($testfct "$@" 2>&1)

	# Failure
	if [ $? -gt 0 ] ; then
		echo failure.
		echo $test_output
		cd $ORIGWD
		exit 1
	fi

	# Success
	echo success. 
}

##############
# CHECK SAME #
##############

# Checks that two files have the same containt
function check_same {

	local file1=$1
	local file2=$2

	if [ -z "$file2" ] ; then
		file2=$file1
	fi
	file1=$file1.output
	file2=$file2.output.ref

	if ! diff $file1 $file2 >/dev/null ; then
		echo "Files $file1 and $file2 are different."
		return 1
	fi

	return 0
}

##################
# RUN SCAN-REPOS #
##################

function run_scanrepos {

	local output_filename=$1
	shift

	$SCANREPOS "$@" >$output_filename.output 2>&1
}

####################
# CHECK SCAN-REPOS #
####################

# Run scan-repos and then check output files
function check_scanrepos {

	local output_filename=$1

	run_scanrepos "$@" || return 1
	check_same $output_filename
}

###########
# RUN GIT #
###########

function run_git {
	git "$@" >/dev/null 2>&1
}

###############
# CLEAN REPOS #
###############

function clean_repos {
	rm -rf repos-*
}


###################
# MAKE BARE REPOS #
###################

function mk_bare_repos {

	local repos=$1

	mkdir $repos
	cd $repos
	run_git init --bare
	cd ..
}

##############
# MAKE REPOS #
##############

function mk_repos {

	local repos="$1"
	local file="$2"

	mkdir "$repos"
	cd "$repos"
	touch "$file"
	run_git init
	run_git add .
	run_git commit -m "Init."
	cd ..
}

#####################
# MODIFY REPOS FILE #
#####################

function modify_repos_file {

	local repos=$1
	local file=$2

	cd $repos
	echo "AAA" >> $file
	run_git add .
	run_git commit -m "Add some text."
	cd ..
}

#####################
# DELETE REPOS FILE #
#####################

function delete_repos_file {

	local repos=$1
	local file=$2

	cd $repos
	rm $file
	run_git add .
	run_git commit -m "Removed file."
	cd ..
}

######################
# TEST MODIFIED FILE #
######################

function test_modified_file {
	clean_repos
	mk_repos repos-a a
	echo "AAA" >> repos-a/a
	check_scanrepos modified_file repos-a || return 1
}

#####################
# TEST DELETED FILE #
#####################

function test_deleted_file {
	clean_repos
	mk_repos repos-a a
	rm repos-a/a
	check_scanrepos deleted_file repos-a || return 1
}

#######################
# TEST UNTRACKED FILE #
#######################

function test_untracked_file {
	clean_repos
	mk_repos repos-a a
	touch repos-a/some_untracked_file.txt
	check_scanrepos untracked_file repos-a || return 1
}

#####################
# TEST BRANCH AHEAD #
#####################

function test_branch_ahead {
	clean_repos
	mk_repos repos-orig a
	run_git clone repos-orig repos-clone
	modify_repos_file repos-clone a
	check_scanrepos branch_ahead repos-clone || return 1
}

######################
# TEST BRANCH BEHIND #
######################

function test_branch_behind {
	clean_repos
	mk_repos repos-orig a
	run_git clone repos-orig repos-clone
	modify_repos_file repos-orig a
	cd repos-clone
	run_git fetch
	cd ..
	check_scanrepos branch_behind repos-clone || return 1
}

##############
# TEST FETCH #
##############

function test_fetch {

	local flags=$1

	clean_repos
	mk_repos repos-orig a
	run_git clone repos-orig repos-clone
	modify_repos_file repos-orig a
	run_scanrepos fetch $flags repos-clone || return 1
	check_same fetch branch_behind || return 1
}

#############
# TEST PULL #
#############

function test_pull {

	local flags=$1

	clean_repos
	mk_repos repos-orig a
	run_git clone repos-orig repos-clone
	modify_repos_file repos-orig a
	check_scanrepos pull $flags repos-clone || return 1
}

#############
# TEST PUSH #
#############

function test_push {

	local flags=$1

	clean_repos
	mk_bare_repos repos-bare
	mk_repos repos-orig a
	cd repos-orig
	run_git remote add origin ../repos-bare
	run_git push -u origin master
	cd ..
	modify_repos_file repos-orig a
	check_scanrepos push $flags repos-orig || return 1
}

######################
# TEST PUSH CONFLICT #
######################

function test_push_conflict {

	local flags=$1

	# Create a bare repos and an orig repos
	clean_repos
	mk_bare_repos repos-bare
	mk_repos repos-orig a
	cd repos-orig
	run_git remote add origin ../repos-bare
	run_git push -u origin master
	cd ..

	# Clone orig repos
	run_git clone repos-orig repos-clone

	# Modify orig repos
	modify_repos_file repos-orig a
	run_scanrepos push_conflict_orig $flags repos-orig || return 1
	check_same push_conflict_orig push || return 1

	# Modify clone repos and try to push
	delete_repos_file repos-clone a
	check_scanrepos push_conflict_clone $flags repos-clone || return 1
}

######################
# TEST PUSH CONFLICT #
######################

function test_unknown_option {

	local flags=$1

	! run_scanrepos unknown_option $flags || return 1
	check_same unknown_option || return 1
}

##################
# TEST REPOSPATH #
##################

function test_repospath {

	# Create a repository with a modified file
	clean_repos
	mk_repos repos-a a
	echo "AAA" >> repos-a/a

	# Outside repository
	check_scanrepos repospath_outside repos-a || return 1

	# Outside repository with environment variable set to repository folder
	REPOSPATH=repos-a run_scanrepos repospath_outside_envvarrepos  || return 1
	check_same repospath_outside_envvarrepos repospath_outside || return 1

	# Outside repository with environment variable set to relative current directory
	REPOSPATH=. check_scanrepos repospath_outside_envvarrelcur  || return 1

	# Outside repository with environment variable unset
	REPOSPATH= run_scanrepos repospath_outside_envvarunset  || return 1
	check_same repospath_outside_envvarunset repospath_outside_envvarrelcur || return 1

	# Inside repository
	cd repos-a
	run_scanrepos ../repospath_inside . || return 1
	cd -
	check_same repospath_inside || return 1

	# Inside repository with environment variable unset
	cd repos-a
	REPOSPATH= run_scanrepos ../repospath_inside_envvarunset  || return 1
	cd -
	check_same repospath_inside_envvarunset repospath_inside || return 1
}

#############################
# TEST MULTIPLE REPOS PATHS #
#############################

function test_multiple_repospaths {

	# Create two repositories with modified files
	clean_repos
	mk_repos repos-a a
	mk_repos repos-b b
	echo "AAA" >> repos-a/a
	echo "AAA" >> repos-b/b

	# Using command line
	check_scanrepos multiple_repospaths repos-a repos-b  || return 1

	# Using environment variable
	REPOSPATH=repos-a:repos-b check_scanrepos multiple_repospaths  || return 1

	# Using default current directory
	REPOSPATH= check_scanrepos multiple_repospaths_curdir  || return 1
}

##############
# TEST SPACE #
##############

function test_space {

	# Create arepository with a modified file
	clean_repos
	mk_repos "repos- a" a
	mk_repos repos-a a
	echo "AAA" >> "repos- a/a"
	echo "AAA" >> repos-a/a

	# One repository with a space character
	check_scanrepos space "repos- a"  || return 1

	# Two repositories with one with a space character
	check_scanrepos space_2_repos "repos- a" repos-a  || return 1
}

###################
# TEST SUBMODULES #
###################

function test_submodules {

	# Create two repositories
	clean_repos
	mk_repos repos-a a
	mk_repos repos-b b
	modify_repos_file repos-a a

	# Add one repository as submodule of the other
	cd repos-b
	run_git submodule add ../repos-a
	run_git commit -m "Add submodule."
	echo "AAA" >> repos-a/a
	cd ..

	check_scanrepos submodules -s repos-b || return 1

	run_git clone --recursive repos-b repos-clone-b
	check_scanrepos submodules_noinit -s -d repos-clone-b || return 1
}

########
# MAIN #
########

cd $SCRIPTDIR
check test_submodules
check test_unknown_option -z
check test_modified_file
check test_deleted_file
check test_untracked_file
check test_branch_ahead
check test_branch_behind
check test_repospath
check test_fetch -f
check test_fetch --fetch
check test_pull -b
check test_pull --pull
check test_push -a
check test_push --push
check test_push_conflict -a
check test_push_conflict --push
check test_multiple_repospaths
check test_space
cd $ORIGWD
