#!/bin/bash

########
# HELP #
########

function help {
	script_name="${0##*/}"
    cat <<EOF
Usage: $script_name <dir_of_git_repositories> <dir_where_to_clone>
Options:
  -h        Print this message and exit.
  -s server Set server to connect to with ssh.
EOF
}

#############
# READ ARGS #
#############

function read_args {

	# set default values
	server=

	# read args
	while getopts "hs:" option; do
    	case "$option" in
			h) help ;;
			s) server=$OPTARG ;;
    	esac
	done
	shift $((OPTIND - 1))

	if (($# > 2 || $# == 0)) ; then
		echo "Wrong number of arguments." >&2
		exit 1
	fi
	repos_dir=$1
	clones_dir=$2
}

#########
# CLONE #
#########

function clone {

	# list repositories
	list_cmd="ls -1 $repos_dir"
	if [ -n "$server" ] ; then
		list_cmd="ssh $server $list_cmd"
	fi

	# clone repositories
	$list_cmd | while read repos ; do
		if [ ! -e "$clones_dir/$repos" ] ; then
			orig="$repos_dir/$repos"
			if [ -n "$server" ] ; then
				orig="$server:$orig"
			fi
			git clone "$orig" "$clones_dir/$repos"
		fi
	done
}

########
# MAIN #
########
read_args "$@"
clone
