#!/usr/bin/env bash

################################################################################
# GET ARGS

# read options
while getopts  "q" flag
do
		case $flag in
				q ) quiet=-q ;;
		esac
done
((nb_read_args=OPTIND - 1))
shift $nb_read_args

# read directory
dir=$1
if [ -z "$dir" ] ; then
		dir=.
fi

################################################################################

find "$dir" -type d -name .git | while read dir ; do 
		echo -e "\nSYNC $dir\n"
		d=`echo $dir | sed 's!/.git$!!'`
		if ! sync-git $quiet "$d" ; then
				echo "Error while syncing local repository $d !" >&2
				exit 2
		fi
done
