#!/usr/bin/env bash

################################################################################
# GET ARGS

# read options
while getopts  "q" flag
do
		case $flag in
				q ) quiet=-q ;;
		esac
done
((nb_read_args=OPTIND - 1))
shift $nb_read_args

# read directory
dir=$1
if [ -z "$dir" ] ; then
		dir=.
fi

################################################################################

for repos in $dir/* ; do 
        if [ -d "$repos/.git" ] ; then
			echo -e "\nSYNC $repos\n"
			if ! sync-git $quiet "$repos" ; then
					echo "Error while syncing local repository $repos !" >&2
					exit 2
			fi
		fi
done
